[{

        intervalTimer: null,
        interval: 10000,
        status_on: true,
        filename: "productionoutputwithtarget.json",
        filesource: "https",
        boxfilename: "productionoutputwithtarget",
        evtype: "productionoutputwithtarget.json",
        rowindex: -1,
        buffer: [],
        fields: "Production",
        buffersize: 1000
    },
    {

        intervalTimer: null,
        interval: 4000,
        status_on: true,
        filename: "LU_measurement_profile",
        filesource: "https",
        boxfilename: "measurement_profile_new",
        evtype: "measurementprofile.json",
        rowindex: -1,
        buffer: [],
        fields: "Machine,Timestamp,Good_Production,Machine_Speed,Rejected",
        buffersize: 1000
    },
    {
        intervalTimer: null,
        interval: 3000,
        status_on: true,
        filename: "HealthyScoreTrend.json",
        filesource: "https",
        boxfilename: "healthscoretrend",
        evtype: "TimeHistory_H1000_LU30.json",
        rowindex: -1,
        buffer: [],
        fields: "Macchina,Timestamp,Health_score",
        buffersize: 1000
    }, {
        intervalTimer: null,
        interval: 1500,
        status_on: true,
        filename: "MAKER_Scarti_sigarette.json",
        boxfilename: "equipmentavailability",
        filesource: "https",
        evtype: "MAKER_Scarti_sigarette.json",
        buffer: [],
        buffersize: 5000,
        rowindex: -1,
        fields: "Availability"
    },
    {
        descr: "anomalylog",
        intervalTimer: null,
        interval: 5000,
        status_on: true,
        filename: "anomalylog.json",
        filesource: "https",
        boxfilename: "anomalylog",
        evtype: "anomalylog.json",
        rowindex: -1,
        buffer: [],
        fields: "glossary,path,typology,True_start",
        buffersize: 2
    },
    {
        descr: "conditionindicators",
        intervalTimer: null,
        interval: 2000,
        status_on: true,
        filename: "conditionindicators.json",
        filesource: "https",
        boxfilename: "conditionindicators",
        evtype: "conditionindicators.json",
        rowindex: -1,
        buffer: [],
        fields: "Nome,Value,Timestamp",
        buffersize: 1000
    },
    {
        descr: "sensormeasurement",
        intervalTimer: null,
        interval: 2000,
        status_on: true,
        filename: "sensor_x1.json",
        filesource: "https",
        boxfilename: "sensor_x1",
        evtype: "sensormeasurement.json",
        rowindex: -1,
        buffer: [],
        fields: "Name,Value,Timestamp",
        buffersize: 1000
    },
    {
        descr: "sensormeasurement",
        intervalTimer: null,
        interval: 4500,
        status_on: true,
        filename: "sensor_x2.json",
        filesource: "https",
        boxfilename: "sensor_x2",
        evtype: "sensormeasurement.json",
        rowindex: -1,
        buffer: [],
        fields: "Name,Value,Timestamp",
        buffersize: 1000
    },
    {
        descr: "sensormeasurement",
        intervalTimer: null,
        interval: 2200,
        status_on: true,
        filename: "sensor_x3.json",
        filesource: "https",
        boxfilename: "sensor_x3",
        evtype: "sensormeasurement.json",
        rowindex: -1,
        buffer: [],
        fields: "Name,Value,Timestamp",
        buffersize: 1000
    },
    {
        descr: "equipmentanomalylog",
        intervalTimer: null,
        interval: 3100,
        status_on: true,
        filename: "LU30_Event Log.json",
        filesource: "https",
        boxfilename: "equipmentanomalylog",
        evtype: "equipmentanomalylog.json",
        rowindex: -1,
        buffer: [],
        fields: "Machine,Timestamp,Glossary",
        buffersize: 1000
    },
    {
        descr: "equipmentfailuremodel",
        intervalTimer: null,
        interval: 4300,
        status_on: true,
        filename: "EquipmentFailurModel.json",
        boxfilename: "equipmentfailuremodel",
        filesource: "https",
        evtype: "equipmentfailurmodel.json",
        rowindex: -1,
        buffer: [],
        fields: "Machine,Model_ID,Model_Name,Score,Execution_Date",
        buffersize: 1000
    }
]